// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {simulation} from '../models';
import {statistics} from '../models';

export function CheckResults():Promise<simulation.SimulationResult>;

export function Greet(arg1:string):Promise<string>;

export function RunSimpleSimulation(arg1:number,arg2:number,arg3:number,arg4:string,arg5:number):Promise<Array<statistics.LearnedSummary>>;
