// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Cancel() {
  return window['go']['main']['App']['Cancel']();
}

export function CheckResults() {
  return window['go']['main']['App']['CheckResults']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function RunSimpleSimulation(arg1, arg2, arg3, arg4, arg5) {
  return window['go']['main']['App']['RunSimpleSimulation'](arg1, arg2, arg3, arg4, arg5);
}
